Some posts
ReCoded-Org/capstone-istanbul-from_garbage_to_gift pull request #11
Opened 2020-10-26 20:02 UTC by betulerkoc

Added SuccessStories component instead of SomePosts component

2020-10-26 21:14 UTC, Luey-A reviewed
Please check the tests as 5 of them are not passing, i also think you didn't run yarn run fix for your code. 
Thank you for the hard work.

2020-10-27 14:39 UTC, Ammar-64 reviewed
can you provide a screenshot and a description of what the code does, so I have a better understanding and visualization

2020-10-28 13:42 UTC, Ammar-64 requested changes

2020-11-09 10:25 UTC, Ammar-64 approved these changes

2020-11-12 11:46 UTC, knargocer approved these changes

2020-11-12 17:40 UTC, merged