Navbar
ReCoded-Org/capstone-istanbul-from_garbage_to_gift pull request #14
Opened 2020-10-27 22:00 UTC by olaouso

![Screenshot (235)](https://user-images.githubusercontent.com/67864177/97364592-563e4200-18b5-11eb-8a0f-e05be4302be0.png)
This code for the Navbar part, it #includes the logo, website pages which are (Home, Posts, donate, about us, contact us) in addition to the search part then three buttons (search, login, sign up).
Also, the navbar included a dropdown list to change the language between EN, AR, or TR.
#14

2020-10-28 15:32 UTC, Ammar-64 requested changes

2020-10-28 15:32 UTC, Ammar-64 commented on src/components/Navbar/index.css
> +.NavC {
what is NavC, classNames should be meaningful even if you have to make them long

2020-10-28 15:32 UTC, Ammar-64 commented on src/components/Navbar/index.css
> +.SignUpButton {
there is to much repetition in both buttons you have to follow DRY rule (don't repeat yourself) so you can do one class for everything mutual in both buttons and you can add the unique things to different classes

2020-10-28 15:32 UTC, Ammar-64 commented on src/components/Navbar/index.css
> +  font-family: "Acme" !important;
your using font-family in every single class while you can use it in all of them at the same time and DRY

2020-10-28 15:32 UTC, Ammar-64 commented on src/components/Navbar/index.jsx
> +      <Navbar.Brand href="#home">
you should use link not href

2020-10-28 15:32 UTC, Ammar-64 commented on src/components/Navbar/index.jsx
> +          <NavDropdown.Item href="#action/3.1">EN</NavDropdown.Item>
what is action/3.1 means

2020-10-28 15:32 UTC, Ammar-64 commented on src/components/Navbar/index.css
> +.LogInButton:visited {
classNames should be camelCases like logInButton

2020-10-28 15:32 UTC, Ammar-64 commented on src/App.jsx
> +import SiteNavbar from "./components/Navbar";
keep a line space between your imports and your components

2020-10-28 20:39 UTC, Luey-A approved these changes

2020-10-28 20:40 UTC, Luey-A requested changes
I request all the changes that were requested by Ammar.

2020-11-01 16:07 UTC, olaouso commented on src/components/Navbar/index.css
> +.NavC {
replaced with NavMain

2020-11-01 17:27 UTC, olaouso commented on src/components/Navbar/index.jsx
> +      <Navbar.Brand href="#home">
link didn't work in bootstrap

2020-11-01 17:27 UTC, olaouso commented on src/components/Navbar/index.jsx
> +          <NavDropdown.Item href="#action/3.1">EN</NavDropdown.Item>
revised

2020-11-06 09:41 UTC, Ammar-64 reviewed
Please resolve the duplication in css, and class names

2020-11-06 09:41 UTC, Ammar-64 commented on src/components/Navbar/index.css
> +.NavMainClass {
classNames should be camelCasses

2020-11-06 09:41 UTC, Ammar-64 commented on src/components/Navbar/index.css
> +  font-family: "Acme" !important;
This is not resolved yet

2020-11-12 11:44 UTC, knargocer approved these changes

2020-11-12 17:15 UTC, olaouso commented on src/components/Navbar/index.css
> +.LogInButton:visited {
done

2020-11-12 17:15 UTC, olaouso commented on src/App.jsx
> +import SiteNavbar from "./components/Navbar";
done

2020-11-12 17:55 UTC, olaouso commented on src/components/Navbar/index.css
> +.SignUpButton {
Done

2020-11-12 17:55 UTC, olaouso commented on src/components/Navbar/index.css
> +  font-family: "Acme" !important;
done

2020-11-12 17:59 UTC, Ammar-64 requested changes
There is one comment resolve it, please

2020-11-12 17:59 UTC, Ammar-64 commented on src/locales/en.json
> +    "Login": "Login",
LogIn should be written like this

2020-11-12 18:14 UTC, olaouso commented on src/locales/en.json
> +    "Login": "Login",
resolved

2020-11-12 18:21 UTC, Ammar-64 requested changes
Fix the links in the navbar please

2020-11-12 18:21 UTC, Ammar-64 commented on src/components/Navbar/index.jsx
> +          <Nav.Link href="#Posts" className="navMainClass">
The links should start with a ”/“ instead of “#”

2020-11-12 18:45 UTC, Ammar-64 approved these changes

2020-11-12 18:55 UTC, olaouso commented
@Luey-A PTAL and approve so the branch can be merged

2020-11-14 15:28 UTC, Luey-A approved these changes

2020-11-14 15:28 UTC, Luey-A commented on src/components/Navbar/index.css
> +border: 1px solid #590995 !important; */
comments should be removed before the pull request

2020-11-14 15:28 UTC, Luey-A commented on src/components/Navbar/__snapshots__/index.test.jsx.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
comments should be removed before the pull request

2020-11-14 15:28 UTC, Luey-A commented on src/App.jsx
> +      <Route path="/Contactus" component={Contactus} /> */}
comments should be removed before the pull request

2020-11-14 15:28 UTC, Luey-A commented on src/components/Navbar/index.css
> +
Do you need this empty line?

2020-11-14 15:28 UTC, Luey-A commented on src/locales/en.json
> +    "Home": "Home",
the above words start with a small letter when these ones starts with a big letter! for example: home in the links and Home in the navbarsection.

2020-11-14 15:34 UTC, merged