Footer
ReCoded-Org/capstone-istanbul-from_garbage_to_gift pull request #15
Opened 2020-10-28 00:10 UTC by orcunsagirsoy

Footer component:

-  add component using mock data

-  add snapshot test

-  logo missing at the right side of the footer

![footer](https://user-images.githubusercontent.com/50768273/97375057-de7b1200-18ca-11eb-8638-40b4411c76b8.PNG)

-footer refactored according to comments

![image](https://user-images.githubusercontent.com/50768273/98012518-3dc8ad00-1e0a-11eb-8cbc-560287ccc4a6.png)

2020-10-28 19:35 UTC, betulerkoc commented on src/components/Footer/index.css
> +/* .address {
we should remove comment lines

2020-10-28 21:54 UTC, Ammar-64 requested changes
you should pull dev and merge it to your branch before because there're some updates there needs to be applied like .eslintrc

2020-10-28 21:54 UTC, Ammar-64 commented on src/components/Footer/index.jsx
> +  explanation: `Lorem Ipsum is simply dummy text of the printing and
don't use lorem ipsum texts

2020-10-28 21:54 UTC, Ammar-64 commented on src/containers/Home/index.jsx
> +      <Footer />
footer is universal it should be imported into app.jsx

2020-10-28 21:54 UTC, Ammar-64 commented on src/components/Footer/index.jsx
> +      <Row className="mainRow">
why are you using to many rows inside each other

2020-10-29 08:40 UTC, orcunsagirsoy commented on src/components/Footer/index.jsx
> +      <Row className="mainRow">
to put the information on separate rows

2020-11-02 12:42 UTC, knargocer reviewed
Dear Orçun,

I don't think you need these many Row and Col tags as well. I think you can even manage it with one row and four columns. You can manage their positions in the row by adding the three contact info items in one div and aligning them with the logo (maybe with display: flex).

Also, as we already have the About us, Contact us, etc buttons in the navbar I guess these are unnecessary in the footer.

Thank you.

2020-11-09 16:50 UTC, Ammar-64 reviewed
Can you please fix the i18n thing

2020-11-09 16:50 UTC, Ammar-64 commented on src/App.jsx
> +    <I18nextProvider i18n={i18n}>
where not using “I18nextProvider i18n={i18n}” where using [useTranslation hook ](https://react.i18next.com/latest/usetranslation-hook)

2020-11-12 11:45 UTC, knargocer approved these changes

2020-11-12 18:13 UTC, orcunsagirsoy commented on src/containers/Home/index.jsx
> +      <Footer />
PTAL

2020-11-12 18:13 UTC, orcunsagirsoy commented on src/components/Footer/index.jsx
> +      <Row className="mainRow">
PTAL

2020-11-12 18:14 UTC, orcunsagirsoy commented on src/App.jsx
> +    <I18nextProvider i18n={i18n}>
PTAL

2020-11-13 11:17 UTC, Ammar-64 approved these changes

2020-11-13 11:17 UTC, Ammar-64 commented
@orcunsagirsoy can you please update the branch, pull dev merge it with footer, fix the conflict and push it agian

2020-11-14 15:55 UTC, Ammar-64 commented
@orcunsagirsoy there are still some conflicts needs to be fixed

2020-11-15 12:27 UTC, merged