Feature/single post pages
ReCoded-Org/capstone-istanbul-from_garbage_to_gift pull request #36
Opened 2020-11-18 18:53 UTC by betulerkoc

- Create SinglePostHeader and SinglePostContent components

- Create SinglePostPage page and render component according to data.

![single-post](https://user-images.githubusercontent.com/40780338/99574459-7d85bc00-29e8-11eb-9ba1-5c0993d02573.png)

2020-11-19 12:11 UTC, Ammar-64 requested changes
Solid work, few comments and we’re good to go but can you delete howItWorks component, it was an example and it unnecessary anymore

2020-11-19 12:11 UTC, Ammar-64 commented on src/components/SinglePostContent/index.jsx
> +        <h2>Target Group</h2>
All texts should be coming from i18next

2020-11-19 12:11 UTC, Ammar-64 commented on src/components/SinglePostHeader/index.jsx
> +          <Button className="backButton" variant="light">
Texts should be coming from i18next

2020-11-21 15:54 UTC, Ammar-64 commented
@betulerkoc there’s a conflict with dev, can you please fix it

2020-11-22 09:02 UTC, Ammar-64 commented
@betulerkoc the post pages are merged now, so you can pull and connect them together

2020-11-22 12:48 UTC, betulerkoc commented on src/components/SinglePostHeader/index.jsx
> +          <Button className="backButton" variant="light">
PTAL

2020-11-22 14:58 UTC, knargocer approved these changes

2020-11-22 15:17 UTC, Ammar-64 requested changes
Solid, some few things and we’re good to go

2020-11-22 15:17 UTC, Ammar-64 commented on src/components/Post/index.jsx
> +        <Link to={"posts/" + postInfo.postInfo.id}>
It’s more convenient to write the link this way,  `<Link to=`posts/${postInfo.postInfo.id}` >`

2020-11-22 15:17 UTC, Ammar-64 commented on src/components/SimilarPosts/index.jsx
> +      <h1 className="text-center title">Similar Posts</h1>
The text here should be coming from i18next, and I don’t think this should be h1

2020-11-22 15:17 UTC, Ammar-64 commented on src/components/SimilarPosts/index.jsx
> +        {similarPostData
You can use slice here like this
`similarPostData
           .slice(0,3)
           .map((data) => {
             return <Post postInfo={data} />;
           }) `

2020-11-22 15:17 UTC, Ammar-64 commented on src/containers/SinglePostPage/index.css
> +.singlePost {
Is this necessary?

2020-11-22 15:17 UTC, Ammar-64 commented on src/containers/SinglePostPage/index.jsx
> +  console.log(id);
No console.log should be in production

2020-11-22 15:17 UTC, Ammar-64 commented on src/components/SimilarPosts/index.jsx
> +  console.log(similarPostData);
No console.log should be in production

2020-11-22 16:38 UTC, betulerkoc commented on src/components/SimilarPosts/index.jsx
> +  console.log(similarPostData);
PTAL

2020-11-22 16:38 UTC, betulerkoc commented on src/containers/SinglePostPage/index.css
> +.singlePost {
PTAL

2020-11-22 17:12 UTC, Ammar-64 approved these changes

2020-11-22 17:12 UTC, merged