New login
ReCoded-Org/capstone-istanbul-from_garbage_to_gift pull request #70
Opened 2020-11-23 19:47 UTC by orcunsagirsoy

Refactor Login Pages

2020-11-23 20:34 UTC, Ammar-64 approved these changes
LGTM

2020-11-23 20:34 UTC, Ammar-64 commented on src/components/LoginPage/GoogleLogin/index.css
> +  width: 17em;
Is this responsive

2020-11-23 20:59 UTC, Ammar-64 requested changes

2020-11-23 20:59 UTC, Ammar-64 commented on src/App.jsx
> +          {/* <Route path="/posts" component={Posts} />
These three lines should be deleted

2020-11-23 20:59 UTC, Ammar-64 commented on src/App.jsx
> +          <Route exact path="/application" />
This should be deleted

2020-11-23 20:59 UTC, Ammar-64 commented on src/components/LoginPage/Login/index.css
> +  width: 17em;
This one too

2020-11-23 21:41 UTC, orcunsagirsoy commented on src/components/LoginPage/Login/index.css
> +  width: 17em;
PTAL

2020-11-23 21:41 UTC, orcunsagirsoy commented on src/App.jsx
> +          <Route exact path="/application" />
PTAL

2020-11-23 21:53 UTC, Ammar-64 approved these changes
LGTM

2020-11-23 21:57 UTC, betulerkoc approved these changes

2020-11-24 00:04 UTC, Ammar-64 approved these changes

2020-11-24 00:04 UTC, merged